### ISSUE TITLE
Request ENR for NodeAddress

### ISSUE THREAD

**Issue by jacobkaufmann** [sigp/discv5#96]
Is it possible to request the `Enr` for a given `NodeAddress`? The [trin](https://github.com/ethereum/trin) portal network client builds multiple overlay networks on top of the base Discovery v5 network. All communications on these overlay networks are via `TalkRequest` messages. The overlay networks rely on `discv5` for session management and message transmission.

When we receive a [ping](https://github.com/ethereum/portal-network-specs/blob/master/portal-wire-protocol.md) from a previously unknown node, we are not able to request the `Enr` for that node, so we cannot add it to our routing table. The [`request_enr` method of `Discv5`](https://github.com/sigp/discv5/blob/master/src/discv5.rs#L413) requires a `TryInto<Multiaddr>`. This method then attempts to convert the `MultiAddr` into a `NodeContact` via [`TryFrom<MultiAddr> for NodeContact`](https://github.com/sigp/discv5/blob/master/src/node_info.rs#L83). That function requires that the `MultiAddr` contain a multi-hash that corresponds to a valid public key for the p2p protocol. However, the associated [`TalkRequest`](https://github.com/sigp/discv5/blob/master/src/service.rs#L54) only contains a [`NodeAddress`](https://github.com/sigp/discv5/blob/master/src/node_info.rs#L150), which does not include public key information.

Is there a way to either (1) add a function to request the `Enr` for a `NodeAddress`, or (2) add additional information to the `TalkRequest` object that would allow us to send such a request?

From my investigations, it seems that there is no trivial way to achieve (1) or (2) without some additional structure in the `Handler` or the `Service`, so I'm opening this issue to get thoughts from the developers.

**Comment by jacobkaufmann** [comment]
Any thoughts/guidance on this?

**Comment by pawanjay176** [comment]
From the portal network wire [specs](https://github.com/ethereum/portal-network-specs/blob/master/portal-wire-protocol.md#find-nodes-0x02), it looks like you can use the `FindNode` message type with `distance == 0` to request the unknown node's enr from the application itself. 

The `request_enr` method does exactly that (sends a discv5 `FindNode` message with `distance == 0`). I might have missed some nuance here as to why you want to make a discv5 request directly instead of through the application layer `FindNode` message.

**Comment by jacobkaufmann** [comment]
The application layer `FindNode` message requires a destination ENR, which is unavailable on an incoming `TalkRequest`. The `TalkRequest` contains a `NodeAddress`, but we cannot map this to an ENR or an appropriate `MultiAddr` for `request_enr`.

**Comment by pawanjay176** [comment]
If the requesting node's message reached the trin overlay network, that would mean that there's already a discv5 session established with that `NodeId` right? They would have already done the discv5 handshake and learned each other's enrs.

You would be able to just query the discv5 DHT with the `find_enr` method in that case.

**Comment by jacobkaufmann** [comment]
This is actually [how we handle things now](https://github.com/ethereum/trin/blob/master/trin-core/src/portalnet/overlay_service.rs#L562), but we want to remove this logic for the concern below. 

Wouldn't this assume that the previously unknown node "fits" in the discv5 routing table? A `trin` node may participate in multiple overlay networks, where none of the individual overlay network routing tables are full, but the underlying discv5 routing table is full with some various assortment of the peers in the overlay routing tables.

I have not dug deep enough into the `Handler`  logic to conclude this, but it seems possible that we could receive a `TalkRequest` from some unknown `NodeId`, where the bucket that the node would otherwise be put into is full, and so that node does not end up in the discv5 routing table, and so the `find_enr` method does not find that node.

Hope this makes sense. I can elaborate further if not.

**Comment by pawanjay176** [comment]
> A `trin` node may participate in multiple overlay networks, where none of the individual overlay network routing tables are full, but the underlying discv5 routing table is full with some various assortment of the peers in the overlay routing tables.

I'm not sure I understand. If your overlay network is receiving messages from any peer via `TalkReq/TalkResp` messages, that would imply that there exists a discv5 session between you and that peer which implies that the peer has to exist in the discv5 routing table as well.

> where the bucket that the node would otherwise be put into is full, and so that node does not end up in the discv5 routing table

I think that in this case, we cannot establish a session with the node to send `TalkReq/TalkResp` messages. Not completely sure though. @AgeManning would have a better idea on this.

**Comment by jacobkaufmann** [comment]
>  If your overlay network is receiving messages from any peer via TalkReq/TalkResp messages, that would imply that there exists a discv5 session between you and that peer which implies that the peer has to exist in the discv5 routing table as well.

This may be a gap in my understanding of those internal `Discv5` mechanics. It would be helpful to understand how a node handles a message from a previously unknown node whose corresponding bucket is full.

Given that Discovery v5 is a base-layer peer discovery protocol, my assumption was that it would be able to handle messages from nodes even if those nodes do not fit into its routing table.

**Comment by AgeManning** [comment]
Hey sorry. I've been on holidays and just returned.

@jacobkaufmann what you're saying is true. If the local routing table is full, we don't store the ENR there for newly connected nodes. We also have an optional filter that manages inbound/outbound and limit the number of inbounds in the routing table to prevent malicious nodes from trying to fill the local routing table with bad nodes. 

For a discv5 handshake we need to do a Diffie Helman handshake which means we need the public key of the node we are trying to send to. If we don't have that we cant send them messages. 

The current design is such that discovery handles all the discovery of nodes. I.e if a million peers connect to us, we dont report these to the user, we only report the peers that the user wishes to find, and only then the safe ones from the request, not all the nodes we find. This is done to prevent eclipse and various other attacks.

So I think (1) is out, because the specification disallows it. 

Lets talk about (2). I'm not fully sure about what you're trying to achieve.

> When we receive a ping from a previously unknown node, we are not able to request the Enr for that node, so we cannot add it to our routing table.

This is a somewhat dangerous practice. If any random user can ping you and you then add them to your routing table, you can get eclipsed pretty easy. In fact a security tester found an issue in an earlier version of this code where they could ping us and we would count their vote for what our IP is. They could then ping us from many accounts and force us to change our local ENR IP to whatever they want. So we had to be more careful with allowing information from random pings.

This is why we have specifically a filter for limiting inbound connections in our routing table.

I personally don't use the `TALKREQ` feature of discv5 and so I'm open to adjusting the user API. However, the change is not trivial because the handler reports the ENR up to the service once a handshake is established then forgets it and only stores session keys (which are used for any future communication). Therefore any future messages, like a TalkReq, the handler only reports the message, which it has decrypted from known session keys and it cant also send the ENR because it doesn't know it. 

Fundamentally, ENRs are only exchanged during the handshake and are either stored in the routing table or subsequently forgotten. So there is a simple change I could propose that might help. 

When a session gets established, we report the ENR up to the service. The service then tries to insert it into the routing table. If it succeeds it emits an event, that the user can optionally obtain: https://github.com/sigp/discv5/blob/master/src/discv5.rs#L60
(I just noticed we don't use the EnrAdded event anymore). 

We could emit events for each ENR we establish a handshake for. i.e and EnrFound event. This way you could just listen to all the events and collect all the ENR's that we come accross and store them in a cache or something and that way you can always contact anyone that contacts you. I would advise against trying to store these in the routing table yourself and let discv5 manage it for you. 

What do you think?

**Comment by jacobkaufmann** [comment]
Appreciate the extensive response. Those are good callouts on the attack vectors, which I overlooked. However, I'm not sure to what extent those attack vectors exist for us at the application layer. Let me try to concretize our use case a bit.

The [Portal Network](https://github.com/ethereum/portal-network-specs) is a collection of overlay networks that exist on top of Discovery v5. Among the overlay networks are networks for distributed storage (e.g. state and history data) and gossip (e.g. transactions and block headers). A node may choose to participate in any subset of these overlay networks.

In our implementation, which initially focuses on the state and history overlay networks, the overlay networks share a common `Discv5` struct. Therefore, they share the same base `Discv5` routing table. The common `Discv5` struct is used to transmit and listen for `Talk` messages on the various overlay networks. Additionally, each overlay network maintains its own protocol-specific routing table. The local node may choose to participate in multiple overlay networks, so we cannot rely on the single underlying `Discv5` routing table to hold all of the cumulative peers from multiple overlay networks in a reasonable manner.

The [portal wire protocol](https://github.com/ethereum/portal-network-specs/blob/master/portal-wire-protocol.md) specifies Ping/Pong/FindNodes/Nodes messages that allow a node to discover peers and maintain its local routing table. These messages are sent via `Talk` messages and are used to populate the protocol-specific routing tables.

The issue is that, if we receive a message from an unknown node on some overlay protocol, and that node cannot be inserted into the underlying `Discv5` routing table (e.g. because the corresponding bucket is full), then we cannot add that node to the overlay routing table, even if there is space for the node there, because we have no way to request its ENR. To my understanding, it sounds like this is not necessarily a problem, and that a node should prefer to establish outgoing connections. Generally, this makes sense, but it seems limiting that a node may not be able to discover an incoming connection, even if it has room in its local (overlay) routing table. Perhaps it is a lack of a strong understanding about the emergent behavior of these networks.

At first thought, I don't think we are vulnerable to the ENR IP address attack that you described above, because we do not have such logic built around our Ping/Pong messages. Our Ping/Pong messages include the source's ENR sequence number and some other protocol-specific information about the node. That's not to say that we would not be vulnerable to other forms of eclipse attacks though.

I think the `EnrFound` event could be useful, because we could map the the `NodeId` in the `TalkRequest` to the ENR. Although, following your points in this discussion, we may need to reevaluate to what extent the issue that I described here is an issue. I hope the additional context may suggest a path forward.

**Comment by AgeManning** [comment]
Thanks for the response. 

I have a better understanding for what you're trying to achieve. Without going to too deep into your protocol, it seems theres a lot of technical edge cases and things you'd need to cover.

The easiest path (for me :) ) is to add an event that just spits out all ENRs from all handshakes that your discv5 server recieves. This way you can do what you like with them. It sounds like you need to bypass the common mechanisms we have in our routing table (pretty much all of these are security-related, so you'd probably have to think about whether bypassing these are harmful to your project or not). 

You could then build the mapping as you say (so you won't have to request it) but also, depending on how you are managing your own routing table, you could just add all these ENR's in there, which gives you access to practically everyone you come accross (you're kind of bypassing the kademlia bucket system and eclipse-resistant design however). 

Because we only store session keys, we can't get the ENR per message, an alternative optional thing we could do is the following (its a bit more overhead however):
- Add another variant to a NodeContact, called something like `OptimisticNodeContact` which only requires a `NodeAddress`. 
- Allow you to send requests with just a `NodeAddress` via an `OptimisticNodeContact`. 

Under the hood, when someone connects to us and sets up a handshake (remember we are dealing with UDP so we dont have long-lived connections) we cache (default is 1000) sessions. So you could try and send a request to the handler and if the session is still in the cache we could send the request with the given session keys. 

I think there are quite a few caveats I've not thought through tho. For example, if the remote has dropped the session, the underlying discv5 tries to re-establish the session and re-send the request, but in this case we can't do that without their public key. So I think we'd run into trouble pretty quick trying to fight the current lower level design with this edge case.

I think any solution we come up with that makes the handler spit out the ENR with a talk request, would be equivalent to getting the ENR in the handshake and storring it in some cache and sending it with the message, which is the same as getting the event and storing it in a mapping at the application layer. 

So I'd be in favour of the ENR event approach if you decide this is something you want/need.

**Comment by jacobkaufmann** [comment]
Those two paths seem equivalent to me, and I would also be in favor of lower complexity at the discv5 layer. I would like to take some time to give it more thought though. If it's alright with the maintainers, then I would prefer that we keep this open for now.
